### ISSUE TITLE
Session Progress stays at 1% although it has finished

### ISSUE THREAD

**Issue by Habush** [MOZI-AI/moses-service#11]
When a run takes too long the session progress is not updated and it stays at 1% although the logs indicate the run is finished

**Comment by Habush** [comment]
Closing this as it couldn't be reproduced and the training session to test the issue it succeeded after 2 days.

**Comment by mjsduncan** [comment]
could their be a bug when the system is running more than one request at a time?  there were 3 separate requests running when the issue happened, and only one completion was indicated on the 3 allocated ports.
